name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: cargo fmt && git diff --exit-code
  test:
    strategy:
      matrix:
        platform: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build

    - name: Test
      run: cargo test
